<?php
$data = array (
  235 => 
  array (
    'cat_id' => '235',
    'cat_name' => '卡客车轮胎',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '3',
    'level' => 0,
    'id' => '235',
    'name' => '卡客车轮胎',
  ),
  246 => 
  array (
    'cat_id' => '246',
    'cat_name' => '螺纹',
    'measure_unit' => '',
    'parent_id' => '235',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '246',
    'name' => '螺纹',
  ),
  245 => 
  array (
    'cat_id' => '245',
    'cat_name' => '直纹',
    'measure_unit' => '',
    'parent_id' => '235',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '245',
    'name' => '直纹',
  ),
  236 => 
  array (
    'cat_id' => '236',
    'cat_name' => '轿车轮胎',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 0,
    'id' => '236',
    'name' => '轿车轮胎',
  ),
  191 => 
  array (
    'cat_id' => '191',
    'cat_name' => '重点展示',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '191',
    'name' => '重点展示',
  ),
);
?>